# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Pokétrader' do

	pod ‘Firebase/Database’
	pod ‘Firebase/Auth’
	pod ‘Firebase/Storage’
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Pokétrader

  target 'PokétraderTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PokétraderUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
